### PR TITLE
Use npm command to find bin path

### LINKED ISSUE #15: Is this method insecure and, if yes, can we use `npm bin` ?
I have seen that this method being allegedly insecure [is a concern in Spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/javascript/README.org#node-modules), where they give a link to [this Stackoverflow thread](https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules#comment33532258_9683472).

An alternative, more secure solution would be to use `npm bin` to find the node_modules.

It would be great if your package could be used by default in Spacemacs, but I fear that this security issue would put off the dev team to do so until it is addressed or debunked.

What do you think about the security issue and the proposed alternative ?

### PR DESCRIPTION
**Pull request by kayhide**
As suggested on #15, this implements `npm bin` version.

Close #15

### CODE REVIEW

**Comment by codesuki** [comment]
Thanks for the PR! I'll review it.

**Comment by codesuki** [comment]
Sorry, I totally lost track of this.

**Comment by kayhide** [comment]
Oh, yeah, finally.
Thanks for accepting the PR!

**Comment by codesuki** [comment]
Thanks for sending it and sorry for taking so long!

**Pull request merged**
